spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

logging.level:
  org.hibernate.SQL: info
