spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

logging.level:
  org.hibernate.SQL: info

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ${AP-NORTHEAST-2}
    stack:
      auto: false

servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB

jwt:
  issuer: test
  secretKey: test
  accessTokenValidTime: 36000000
  refreshTokenValidTime: 36000000
