spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging.level:
  org.hibernate.type: trace
