spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bikeWatch
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
